---
title: "Untitled"
output: pdf_document
---

\begin{raggedleft}
{\bf Acknowledgments}
\end{raggedleft}

First of all I would like to thank Prof. Dr. Ulrich Kulozik for his advise and supervistion for this project as well as for his patience and giving me the possibility to perform this work. In addition, I would like to thank the whole ZIEL\footnote{Zentralinstitut für Ernährungs- und Lebensmittelforschung}  Institute for Food and Health as well as the Institute for Food- and Bio-process Engineering for their support and scientific insight during the experimental part of this work. A special thanks goes to Mrs. Heidi Wohlschläger who gave much needed insight towards the HPLC measurement methods performed in this study. 

Additionally I would like to thank my mentor for this thesis, Dr.rer.nat. Alexander Buchner.

Also, I would like to thank my office colleagues, Dr. Martin Hartinger, Dr. Christian Kleemann, Franz Fraunhofer and Michael Reitmeier for the good communication and collaboration. A special thanks goes to Mrs. Franziska Kurz, who was always available as a sometimes needed friend during this work, as well as a discussion partner in scientific terms.

A special honoration goes to my students, Christina Baumeister, Alexander Schmieder and Viktoria Heitler for their tireless work during method development and their fierce interest in the science that is processed cheese. The liberating discussions as well as their considerations towards the experimental results helped a lot to shape this work.

Also, I want to thank my family and friends, who are always true believers in me and never doubt me to achieve my goals. Without them, this thesis would not have been possible.
